spring:
  data:
    redis:
      host: redis
      port: 6379
      database: 0
  config:
    activate:
      on-profile: prod
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://mariadb_container:3306/hotels_db
    username: hotels_user
    password: hotels12345

# 파일 업로드 설정
file:
  upload:
    hotel:
      path: ./uploads/hotelimage/    # 기존 static 폴더에서 읽기만
      resourceHandler: /hotel-images/**
    user:
      path: ./uploads/userimage/            # 업로드 및 읽기
      resourceHandler: /user-images/**
      webPath: /user-images/
    parlor:
      path: ./uploads/parlorimage/    # 기존 static 폴더에서 읽기만
      resourceHandler: /parlor-images/**
# 프로젝트 기본 경로 설정 (필요한 경우)
#JPA log
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        orm:
          jdbc:
            bind: TRACE

cors:
  allowed-origins: http://localhost:443,http://localhost:80,http://mjc813b.softagape.com/,https://mjc813b.softagape.com/, http://localhost:8080