spring:
  data:
    redis:
      host: redis
      port: 6379
      database: 0
  config:
    activate:
      on-profile: prod
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://mariadb_container:3306/hotels_db
    username: hotels_user
    password: hotels12345

file:
  upload:
    hotel:
      path: /app/uploads/hotelimage/
      resourceHandler: /hotel-images/**
    user:
      path: /app/uploads/userimage/      # Docker 컨테이너 내부 경로
      resourceHandler: /user-images/**
      webPath: /user-images/

#JPA log
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        orm:
          jdbc:
            bind: TRACE

cors:
  allowed-origins: http://localhost:3000,http://localhost:80,http://mjc813b.softagape.com/,https://mjc813b.softagape.com/