spring:
  data:
    redis:
      host: localhost
      port: 16379
      database: 0
  config:
    activate:
      on-profile: local

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:13306/hotels_db
    username: hotels_user
    password: hotels12345

# 파일 업로드 설정
file:
  upload:
    hotel:
      path: classpath:static/hotelimage/    # 기존 static 폴더에서 읽기만
      resourceHandler: /hotel-images/**
    user:
      path: ./uploads/userimage/            # 업로드 및 읽기
      resourceHandler: /user-images/**
      webPath: /user-images/
    parlor:
      path: classpath:static/parlorimage/    # 기존 static 폴더에서 읽기만
      resourceHandler: /parlor-images/**
# 프로젝트 기본 경로 설정 (필요한 경우)
project:
  basedir: .


#JPA log
logging:
  level:
    org:
        SQL: DEBUG
        orm:
          jdbc:
            bind: TRACE
cors:

  allowed-origins: http://localhost:8080, http://localhost:8085, http://tomhoon.my:780

